framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true

#The Templating Component itself is not deprecated, the integration with the FrameworkBundle is deprecated. So removing that option is enough.
    templating:
#        engines: ['php']
        engines: ['twig', 'php']
