index:
  path: /
  controller: App\Controller\DefaultController::indexAction

public:
  path: /public
  controller: App\Controller\DefaultController::indexAction


backend_admin_homepage:
  path:     /
  controller: App\Controller\DefaultController::indexAction
