#index:
#    path: /
#    controller: App\Controller\DefaultController::index


backend_admin_homepage:
  path:     /
  controller: App\Controller\DefaultController::indexAction



backend_admin_gauge:
  path:     /gauge
  controller: App\Controller\DefaultController::gaugeAction